import React from "react";

const Term = () => {
  const containerStyle = {
    padding: "2rem",
    maxWidth: "900px",
    margin: "auto",
    fontFamily: "Arial, sans-serif",
    color: "#333",
    lineHeight: "1.6",
    backgroundColor: "#f9f9f9",
    borderRadius: "12px",
    boxShadow: "0 0 10px rgba(0,0,0,0.1)"
  };

  const headingStyle = {
    textAlign: "center",
    fontSize: "2.5rem",
    fontWeight: "bold",
    color: "#0077cc",
    marginBottom: "1rem"
  };

  const sectionHeadingStyle = {
    textAlign: "center",
    fontSize: "1.8rem",
    fontWeight: "600",
    marginBottom: "1rem"
  };

  const paragraphStyle = {
    marginBottom: "1rem",
    fontSize: "1rem"
  };

  const highlightStyle = {
    ...paragraphStyle,
    fontWeight: "bold",
    color: "#cc0000"
  };

  const listStyle = {
    paddingLeft: "1.5rem",
    marginTop: "1rem"
  };

  const linkStyle = {
    textDecoration: "none",
    color: "#0077cc",
    fontWeight: "500"
  };

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Lord Glory</h1>
      <h2 style={sectionHeadingStyle}>Terms & Conditions</h2>

      <div>
        <p style={paragraphStyle}>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>

        <p style={paragraphStyle}>
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of domain name{" "}
          <a
            href="https://www.lordglory.in"
            target="_blank"
            rel="noopener noreferrer"
            style={linkStyle}
          >
            https://www.lordglory.in
          </a>{" "}
          ('Website'), including the related mobile site and mobile application
          (hereinafter referred to as 'Platform').
        </p>

        <p style={paragraphStyle}>
          The Platform is owned by B S SALES AND MARKETING, a company
          incorporated under the Companies Act, 1956 with its registered office
          at Morshi, AMARAVATI MAHARASTRA, India (hereinafter referred to as
          'Platform Owner', 'we', 'us', 'our').
        </p>

        <p style={paragraphStyle}>
          Your use of the Platform and services and tools are governed by the
          following terms and conditions ("Terms of Use") as applicable to the
          Platform including the applicable policies which are incorporated
          herein by way of reference. If You transact on the Platform, You shall
          be subject to the policies that are applicable to the Platform for
          such transaction. By mere use of the Platform, You shall be
          contracting with the Platform Owner and these terms and conditions
          including the policies constitute Your binding obligations, with
          Platform Owner. These Terms of Use relate to your use of our website,
          goods (as applicable) or services (as applicable) (collectively,
          'Services').
        </p>

        <p style={paragraphStyle}>
          Any terms and conditions proposed by You which are in addition to or
          which conflict with these Terms of Use are expressly rejected by the
          Platform Owner and shall be of no force or effect.
        </p>

        <p style={paragraphStyle}>
          These Terms of Use can be modified at any time without assigning any
          reason. It is your responsibility to periodically review these Terms
          of Use to stay informed of updates.
        </p>

        <p style={paragraphStyle}>
          For the purpose of these Terms of Use, wherever the context so
          requires 'you', 'your' or 'user' shall mean any natural or legal
          person who has agreed to become a user/buyer on the Platform.
        </p>

        <p style={highlightStyle}>
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
          AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
          PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </p>

        <p style={paragraphStyle}>
          The use of Platform and/or availing of our Services is subject to the
          following Terms of Use:
        </p>

        <ol style={listStyle}>
          <li>You agree to provide true, accurate and complete information.</li>
          <li>We don’t guarantee accuracy, timeliness or completeness of content.</li>
          <li>Use our platform at your own discretion and risk.</li>
          <li>All platform content is proprietary to us.</li>
          <li>Unauthorized use may lead to legal action.</li>
          <li>You agree to pay applicable service charges.</li>
          <li>You won’t use the platform for unlawful purposes.</li>
          <li>Links to third-party sites are provided for convenience only.</li>
          <li>Using our service forms a binding contract with us.</li>
          <li>You agree to indemnify us for violations.</li>
          <li>We’re not liable for force majeure events.</li>
          <li>Disputes are governed by Indian law.</li>
          <li>Jurisdiction lies in Morshi, Maharashtra.</li>
          <li>Contact us via our official website for concerns.</li>
        </ol>
      </div>
    </div>
  );
};

export default Term;
